# Generated by Django 2.0.4 on 2018-04-08 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('texto', models.TextField()),
                ('imagem_pequena', models.ImageField(upload_to='images/')),
                ('imagem_grande', models.ImageField(upload_to='images/')),
                ('url_comentarios', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
