# Generated by Django 2.0.4 on 2018-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castnautas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem_carrossel',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
