# Generated by Django 2.0.4 on 2018-04-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castnautas', '0002_postagem_imagem_carrossel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagem_carrossel',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem_grande',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem_pequena',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='url_comentarios',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
