# Generated by Django 2.0.4 on 2018-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castnautas', '0006_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
