# Generated by Django 2.0.4 on 2018-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castnautas', '0007_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
