# Generated by Django 2.0.4 on 2018-04-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castnautas', '0008_auto_20180408_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='postagens',
        ),
        migrations.AddField(
            model_name='postagem',
            name='categorias',
            field=models.ManyToManyField(to='castnautas.Categoria'),
        ),
    ]
