# Generated by Django 2.0.4 on 2018-04-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castnautas', '0009_auto_20180408_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='castnautas.Categoria'),
        ),
    ]
