# Generated by Django 2.0.4 on 2018-04-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castnautas', '0010_auto_20180408_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='resumo',
            field=models.TextField(blank=True, max_length=187),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=144),
        ),
    ]
